#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mumble-web"
name = "Mumble Web"
description.en = "Web interface for voice chat software (VoIP)"
description.fr = "Interface web pour voix sur IP (VoIP)"

version = "1.3.0~ynh6"

maintainers = []

[upstream]
license = "BSD-3-Clause"
website = "https://mumble.info"
demo = "https://web.mumble.framatalk.org/"
admindoc = "https://docs.framasoft.org/fr/jitsimeet/mumble.html"
code = "https://github.com/Johni0702/mumble-web/"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "1500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/Johni0702/mumble-web/archive/4ef594c8a097d180700d22d91e9a7fea3bab08ac.tar.gz"
    sha256 = "27ced80fc7a3035af531226658903ecd8a18881e045ebb5684d0a503ef67fb1d"
    autoupdate.upstream = "https://github.com/Johni0702/mumble-web"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 64737

    [resources.apt]
    packages = ["websockify"]
