#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

path="/"

# Testing if mumbleserver is installed
yunohost app list | grep -q "id: mumbleserver" || ynh_die "mumble-server is needed, but it is not installed."

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing NodeJS..."

ynh_nodejs_install

#=================================================
# INSTALL Mumble-web
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source
ynh_setup_source --dest_dir="$install_dir"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:www-data" "$install_dir"
#=================================================
# BUILD CODE
#=================================================
ynh_script_progression "Building Mumble web client..."

pushd "$install_dir"

    ynh_hide_warnings ynh_exec_as_app node_load_PATH" npm install --save --loglevel warn
    ynh_hide_warnings ynh_exec_as_app node_load_PATH" npm run build
popd

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.local.js" --destination="$install_dir/dist/config.local.js"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 400 "$install_dir/dist/config.local.js"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown "$app" "$install_dir/dist/config.local.js"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add "$app" --description="Mumble web client" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action=restart --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
